version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: transpo_service_production
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - transpo_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    command: bundle exec rails s -b '0.0.0.0' -p 3000
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://postgres@db:5432/transpo_service_production
    env_file:
      - .env.production
    depends_on:
      - db

  delayed_job:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    command: bundle exec rake jobs:work
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://postgres@db:5432/transpo_service_production
    env_file:
      - .env.production
    depends_on:
      - db
      - web

  webpush:
    build:
      context: ./webpush-server
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
    command: npm run prod
    ports:
      - "9090:9090"
    env_file:
      - .env.production

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - webpush
    environment:
      NGINX_HOST: transpo.mcgi.services

volumes:
  transpo_data:
