# Stage 1: Build the application
FROM node:18 AS build

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install --production

COPY . .

# Stage 2: Serve the application
FROM node:18-slim

WORKDIR /usr/src/app

# Copy from build stage
COPY --from=build /usr/src/app /usr/src/app

# Expose the port the app runs on
EXPOSE 3000

# Set NODE_ENV to production
ENV NODE_ENV=production

# Command to run the app
CMD ["node", "server.js"]
